"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_=1723&ea+jkt1c(rf2ez6ur+m)%olhfu@v(i-@95&xu#$o^rx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',                  # 跨域资源共享 +
    'rest_framework',               # rest_framework-API+
    'rest_framework_simplejwt',     # jwt
    'django_filters',               # 过滤器
    'drf_yasg',                     # 接口文档
    'App.apps.AppConfig',           # 应用
    'csp'                           # 控制
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 跨源 +
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'application.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Django_Vben',              # 数据库名
        'USER': 'root',                     # 用户
        'PASSWORD': '123456',                 # 密码
        'HOST': '127.0.0.1',                # host
        'PORT': '3306',                     # port
        'OPTIONS': {
            'charset': 'utf8mb4',
        }
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'App.User'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# 配置media资源路径 +
import os
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# 配置 REST_FRAMEWORK 
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # ...
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

## 安全配置

CORS_ORIGIN_ALLOW_ALL = False  # 不要允许所有来源
CORS_ALLOW_CREDENTIALS = True  # 只有在严格控制的来源下才启用
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5777",
]

# CSRF配置
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:5777",

]

CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'connect-src': ("'self'", 'http://127.0.0.1:5777/'),
        'default-src': ("'self'", 'http://127.0.0.1:5777'),
        'font-src': ("'self'",'data:','https://fonts.gstatic.com','http://127.0.0.1:5777'),
        'frame-ancestors': ("'self'", 'http://127.0.0.1:5777'),
        'frame-src': ("'self'", 'http://127.0.0.1:5777'),
        'img-src': ("'self'", 'data:', 'http://127.0.0.1:5777'),
        'media-src': ("'self'", 'http://127.0.0.1:5777'),
        'object-src': ("'none'", 'http://127.0.0.1:5777'),
        'script-src': ("'self'", 'blob:', "'unsafe-inline'", 'http://127.0.0.1:5777'),
        'style-src': ("'self'","'unsafe-inline'",'https://fonts.googleapis.com','http://127.0.0.1:5777'),
        'worker-src': ("'self'", 'blob:', 'http://127.0.0.1:5777')
    }
}

APPEND_SLASH=False