# Generated by Django 5.2.5 on 2025-08-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='homePath',
            field=models.CharField(default='/profile/info', max_length=255, verbose_name='Home path'),
        ),
    ]
